FROM amazonlinux:2.0.20230808.0

RUN yum -y update && \
    yum -y install git && \
    yum -y install wget && \
    yum -y group install "Development Tools" && \
    yum -y install gdb && \
    yum -y install openssl openssl-devel && \
    yum -y install zip && \
    yum -y install libcurl-devel && \
    yum -y install libuuid-devel && \
    yum -y install openssh-server && \
    yum -y install python3 && \
    yum  clean all && \
    mkdir /var/run/sshd && \
    echo 'root:aws' | chpasswd && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i '/#PermitRootLogin prohibit-password/i PermitRootLogin yes' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    ssh-keygen -t rsa -b 4096 -f ssh_host_rsa_key && \
    cp ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key && \
    cd /opt && \
    wget https://github.com/Kitware/CMake/releases/download/v3.26.5/cmake-3.26.5.tar.gz && \
    tar -zxvf cmake-3.26.5.tar.gz && \
    cd cmake-3.26.5 && \
    ./bootstrap && \
    make && \
    make install && \
    cmake --version && \
    cd .. && \
    rm cmake-3.26.5.tar.gz && \
    rm -rf cmake-3.26.5 && \
    cd /opt && \
    git clone https://github.com/llvm/llvm-project.git && \
    cd llvm-project && \
    git checkout llvmorg-16.0.0 && \
    mkdir build && \
    cd build && \
    cmake -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;lldb" LLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf llvm-project && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i '/#PermitRootLogin prohibit-password/i PermitRootLogin yes' /etc/ssh/sshd_config

ENV C=/usr/local/bin/clang
ENV CC=/usr/local/bin/clang++

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
